// One-shot module load verification (temp script)
const m = await import('file:///C:/dsh-reactor/lib/index.js')
console.log('name:', m.name)
console.log('inject:', JSON.stringify(m.inject))
console.log('Config ok:', typeof m.Config === 'function')
console.log('apply ok:', typeof m.apply === 'function')
const s = await import('file:///C:/dsh-reactor/lib/store.js')
console.log('RuleStore ok:', typeof s.RuleStore === 'function', '| HistoryStore ok:', typeof s.HistoryStore === 'function')
const w = await import('file:///C:/dsh-reactor/lib/webhook-server.js')
console.log('registerWebhookIngress ok:', typeof w.registerWebhookIngress === 'function')
const a = await import('file:///C:/dsh-reactor/lib/agent-session.js')
console.log('runAgentSession ok:', typeof a.runAgentSession === 'function')
process.exit(0)
